import {env} from 'cloudflare:workers';
import {Buffer} from 'node:buffer';
const cfg=()=>env as unknown as Record<string,string>;
export function gmailConfigured(){const c=cfg();return ['GOOGLE_CLIENT_ID','GOOGLE_CLIENT_SECRET','GOOGLE_REFRESH_TOKEN','GMAIL_SENDER','CMO_OWNER_USER_ID'].every(k=>!!c[k])}
export function ownerConfigured(userId:string){return cfg().CMO_OWNER_USER_ID===userId}
export async function gmailToken(){const c=cfg();if(!gmailConfigured())throw new Error('Gmail is not configured. Set up the authorized business mailbox first.');const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:c.GOOGLE_CLIENT_ID,client_secret:c.GOOGLE_CLIENT_SECRET,refresh_token:c.GOOGLE_REFRESH_TOKEN,grant_type:'refresh_token'}),signal:AbortSignal.timeout(15000)});const j:any=await r.json();if(!r.ok||!j.access_token)throw new Error('Gmail authorization failed. Reconnect the business mailbox.');return j.access_token as string}
export async function gmailRequest(path:string,token:string,init:RequestInit={}){const r=await fetch('https://gmail.googleapis.com/gmail/v1/users/me/'+path,{...init,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json',...init.headers},signal:AbortSignal.timeout(15000)});if(!r.ok)throw new Error('Gmail request failed ('+r.status+'). Check connection health before retrying.');return await r.json() as any}
export async function health(){const token=await gmailToken();const p=await gmailRequest('profile',token);if(p.emailAddress?.toLowerCase()!==cfg().GMAIL_SENDER.toLowerCase())throw new Error('Configured sender does not match the authorized Gmail account.');return {email:p.emailAddress,verifiedAt:new Date().toISOString()}}
export function mime(to:string,subject:string,body:string,id:string,replyToId?:string){const sender=cfg().GMAIL_SENDER;if(!/^[^\s@<>]+@[^\s@<>]+\.[^\s@<>]+$/.test(to)||/[\r\n]/.test(sender+to+subject))throw new Error('Invalid recipient or email header.');const message=['From: '+sender,'To: '+to,'Subject: =?UTF-8?B?'+Buffer.from(subject).toString('base64')+'?=','Message-ID: <'+id+'@gosakha-cmo.local>',...(replyToId?['In-Reply-To: <'+replyToId+'@gosakha-cmo.local>','References: <'+replyToId+'@gosakha-cmo.local>']:[]),'MIME-Version: 1.0','Content-Type: text/plain; charset=UTF-8','Content-Transfer-Encoding: base64','',Buffer.from(body).toString('base64').match(/.{1,76}/g)?.join('\r\n')||''].join('\r\n');return Buffer.from(message).toString('base64url')}
export async function threadHasReply(threadId:string,token:string){const thread=await gmailRequest('threads/'+encodeURIComponent(threadId)+'?format=metadata&metadataHeaders=From',token);return (thread.messages||[]).some((m:any)=>!(m.labelIds||[]).includes('SENT')&&!(m.labelIds||[]).includes('DRAFT'))}
