import {readState,saveState} from './storage';
import {record,uid,type State,type Item} from '../../shared/model';
import {gmailToken,gmailRequest,mime,threadHasReply,health} from './gmail';
import {assertSendable,reservationCanSend} from './outreach-policy';
export async function syncReplies(key:string,token:string){const snapshot=await readState(key,false);let changed=false;for(const email of snapshot.state.items.filter(i=>i.kind==='email'&&i.status==='Sent'&&i.threadId).slice(0,50)){if(await threadHasReply(email.threadId!,token)){const l=snapshot.state.leads.find(l=>l.id===email.leadId);if(!l)continue;email.status='Replied';snapshot.state.items.filter(i=>i.leadId===l.id&&['email','sequence'].includes(i.kind)&&['Approved','Pending approval','Waiting for initial send','Active'].includes(i.status)).forEach(i=>i.status='Stopped');l.nextAction='Review new Gmail reply before further outreach';if(!snapshot.state.items.some(i=>i.kind==='reply'&&i.threadId===email.threadId))snapshot.state.items.unshift({id:uid(),kind:'reply',title:'New reply · '+l.name,body:'Gmail confirmed a reply in the outreach thread. Content is not imported. Open Gmail to review and record the classification here.',status:'Needs review',channel:'Email',leadId:l.id,due:'',createdAt:new Date().toISOString(),source:'Gmail thread metadata',threadId:email.threadId});record(snapshot.state,'EMAIL_REPLY_RECEIVED','Gmail Agent','Reply received from '+l.name+'; sequence stopped',l.id);changed=true}}if(changed)await saveState(key,snapshot.state,snapshot.revision,snapshot.exists);return changed}
export async function sendApproved(key:string,id:string){await health();const token=await gmailToken();await syncReplies(key,token);let snap=await readState(key,false);const item=snap.state.items.find(i=>i.id===id);const lead=assertSendable(snap.state,item);const i=item!;if(i.threadId&&await threadHasReply(i.threadId,token))throw new Error('A reply was found. Review it before further outreach.');const first=i.sequenceId?snap.state.items.find(x=>x.sequenceId===i.sequenceId&&x.step===0):undefined;const raw=mime(lead.email,first?.title||i.title,i.body,i.id,i.step&&first?first.id:undefined);i.status='Sending';i.sentAt=new Date().toISOString();record(snap.state,'EMAIL_SEND_STARTED','Gmail Agent','Sending approved email to '+lead.name,i.id);await saveState(key,snap.state,snap.revision,snap.exists);
 // Recheck the committed reservation before the external side effect. A racing opt-out fails closed.
 snap=await readState(key,false);if(!reservationCanSend(snap.state,id)){const reserved=snap.state.items.find(x=>x.id===id);if(reserved?.status==='Sending'){reserved.status='Stopped';reserved.sentAt=undefined;record(snap.state,'EMAIL_SEND_CANCELLED','Gmail Agent','Sending stopped before contacting Gmail.',id);await saveState(key,snap.state,snap.revision,snap.exists)}throw new Error('Sending stopped after a concurrent workspace change.');}
 let result:any;try{result=await gmailRequest('messages/send',token,{method:'POST',body:JSON.stringify({raw,...(i.threadId?{threadId:i.threadId}:{})})})}catch{const latest=await readState(key,false);const current=latest.state.items.find(x=>x.id===id);if(current?.status==='Sending'){current.status='Delivery uncertain';record(latest.state,'WORKFLOW_FAILED','Gmail Agent','Delivery uncertain. Check Gmail before any further send.',id);await saveState(key,latest.state,latest.revision,latest.exists)}throw new Error('Gmail delivery could not be confirmed. Check the sent mailbox before retrying; automatic retries are blocked.');}
 // Only retry the persistence step, never the provider send.
 for(let attempt=0;attempt<3;attempt++){const latest=await readState(key,false);const current=latest.state.items.find(x=>x.id===id);if(!current)throw new Error('Sent email record unavailable.');current.status='Sent';current.providerId=result.id;current.threadId=result.threadId;current.sentAt=new Date().toISOString();const l=latest.state.leads.find(l=>l.id===i.leadId);if(l&&l.stage==='New'){l.stageHistory=[...(l.stageHistory||[{stage:l.stage,at:l.updatedAt}]),{stage:'Contacted',at:current.sentAt}];l.stage='Contacted';l.updatedAt=current.sentAt;}if(current.sequenceId){const seq=latest.state.items.find(x=>x.id===current.sequenceId);if(seq&&seq.status!=='Stopped'){seq.status=current.step===2?'Completed':'Active';const next=latest.state.items.find(x=>x.sequenceId===current.sequenceId&&x.step===(current.step||0)+1);if(next){next.due=new Date(Date.now()+(next.delayDays||2)*86400000).toISOString();next.threadId=result.threadId}}}record(latest.state,'EMAIL_SENT','Gmail Agent','Gmail confirmed email sent to '+lead.name,id);try{await saveState(key,latest.state,latest.revision,latest.exists);return {sent:true}}catch(e){if(attempt===2)throw e}}return {sent:true};}
