// Fixed provider origins. Tokens are server-only; responses never expose credentials.
export type Config=Record<string,string>;
export async function requestJSON(url:string,init:RequestInit={},fetcher:typeof fetch=fetch){const r=await fetcher(url,{...init,signal:AbortSignal.timeout(20000)});if(!r.ok)throw new Error('Provider request failed (HTTP '+r.status+'). Check authorization and provider permissions.');return {data:await r.json() as any,headers:r.headers};}
export async function linkedinPublish(c:Config,body:string,fetcher=fetch){
 if(!/^urn:li:(person|organization):[A-Za-z0-9_-]+$/.test(c.LINKEDIN_AUTHOR_URN))throw new Error('Set a valid LinkedIn author URN.');if(!/^\d{6}$/.test(c.LINKEDIN_VERSION))throw new Error('Set a supported LinkedIn API version (YYYYMM).');
 const r=await fetcher('https://api.linkedin.com/rest/posts',{method:'POST',headers:{Authorization:'Bearer '+c.LINKEDIN_ACCESS_TOKEN,'Content-Type':'application/json','LinkedIn-Version':c.LINKEDIN_VERSION,'X-Restli-Protocol-Version':'2.0.0'},body:JSON.stringify({author:c.LINKEDIN_AUTHOR_URN,commentary:body,visibility:'PUBLIC',distribution:{feedDistribution:'MAIN_FEED',targetEntities:[],thirdPartyDistributionChannels:[]},lifecycleState:'PUBLISHED',isReshareDisabledByAuthor:false}),signal:AbortSignal.timeout(20000)});
 if(!r.ok)throw new Error('LinkedIn publishing failed (HTTP '+r.status+').');const id=r.headers.get('x-restli-id');if(!id)throw new Error('LinkedIn did not return a publication ID.');return id;
}
export function instagramBase(c:Config){if(!/^v\d+\.\d+$/.test(c.META_GRAPH_VERSION)||!/^\d+$/.test(c.INSTAGRAM_ACCOUNT_ID))throw new Error('Set a supported Graph version and Instagram professional account ID.');return 'https://graph.facebook.com/'+c.META_GRAPH_VERSION;}
export async function instagramContainer(c:Config,body:string,image:string,fetcher=fetch){const u=new URL(image);if(u.protocol!=='https:')throw new Error('Instagram requires a publicly reachable HTTPS image URL.');const r=await requestJSON(instagramBase(c)+'/'+c.INSTAGRAM_ACCOUNT_ID+'/media',{method:'POST',headers:{Authorization:'Bearer '+c.INSTAGRAM_ACCESS_TOKEN,'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({image_url:image,caption:body})},fetcher);if(!r.data.id)throw new Error('Instagram returned no media container.');return String(r.data.id);}
export async function instagramReady(c:Config,container:string,fetcher=fetch){const status=await requestJSON(instagramBase(c)+'/'+encodeURIComponent(container)+'?fields=status_code',{headers:{Authorization:'Bearer '+c.INSTAGRAM_ACCESS_TOKEN}},fetcher);if(status.data.status_code!=='FINISHED')throw new Error('Media is not ready. Wait for processing, then retry publishing.');}
export async function instagramPublish(c:Config,container:string,fetcher=fetch){const base=instagramBase(c);const headers={Authorization:'Bearer '+c.INSTAGRAM_ACCESS_TOKEN};const status=await requestJSON(base+'/'+encodeURIComponent(container)+'?fields=status_code',{headers},fetcher);if(status.data.status_code!=='FINISHED')throw new Error('Media is not ready: '+String(status.data.status_code||'unknown')+'. Check preparation again before publishing.');const result=await requestJSON(base+'/'+c.INSTAGRAM_ACCOUNT_ID+'/media_publish',{method:'POST',headers:{...headers,'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({creation_id:container})},fetcher);if(!result.data.id)throw new Error('Instagram returned no publication ID.');return String(result.data.id);}
export async function calendarEvent(c:Config,token:string,i:{id:string;title:string;body:string;due:string},email:string,fetcher=fetch){
 if(!i.due||Date.parse(i.due)<=Date.now())throw new Error('Choose a future meeting time.');const url='https://www.googleapis.com/calendar/v3/calendars/'+encodeURIComponent(c.GOOGLE_CALENDAR_ID||'primary')+'/events';const id=i.id.replaceAll('-','').toLowerCase();if(!/^[0-9a-f]{32}$/.test(id))throw new Error('Create a live meeting record before sending an invite.');
 const r=await requestJSON(url+'?sendUpdates=all',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({id,summary:i.title,description:i.body,start:{dateTime:i.due},end:{dateTime:new Date(Date.parse(i.due)+30*60000).toISOString()},attendees:[{email}]})},fetcher);return {id:String(r.data.id),url:r.data.htmlLink};
}
export async function research(c:Config,query:string,fetcher=fetch){const result=await requestJSON('https://api.search.brave.com/res/v1/web/search?q='+encodeURIComponent(query)+'&count=6',{headers:{'X-Subscription-Token':c.BRAVE_SEARCH_API_KEY,Accept:'application/json'}},fetcher);return (result.data.web?.results||[]).slice(0,6).filter((r:any)=>typeof r.url==='string'&&/^https?:\/\//.test(r.url)).map((r:any)=>({title:String(r.title).slice(0,180),source:r.url,body:String(r.description||'Read the original source before using this result.').replace(/<[^>]*>/g,'').slice(0,3000)}));}
export async function claude(c:Config,system:string,input:string,fetcher=fetch){const r=await requestJSON('https://api.anthropic.com/v1/messages',{method:'POST',headers:{'x-api-key':c.ANTHROPIC_API_KEY,'anthropic-version':'2023-06-01','Content-Type':'application/json'},body:JSON.stringify({model:c.ANTHROPIC_MODEL,max_tokens:2500,system,messages:[{role:'user',content:input}]})},fetcher);const text=(r.data.content||[]).filter((x:any)=>x.type==='text').map((x:any)=>x.text).join('');try{return JSON.parse(text.replace(/^```(?:json)?\s*|\s*```$/g,''))}catch{throw new Error('AI output was not valid structured JSON. No actions were created.');}}
