import {reservationCanSend} from '../backend/services/outreach-policy.ts';
import test from 'node:test';
import assert from 'node:assert/strict';
import {authorize,validateMember} from '../backend/services/permissions.ts';
import {initialState,mutate} from '../shared/model.ts';
for(const [role,action,id,kind] of [['Content Reviewer','approval.decide','draft-1','post'],['Sales','item.edit','post-1','task'],['Content Reviewer','item.submit','draft-1','post']])test(`${role} cannot spoof target kind for ${action}`,()=>assert.throws(()=>authorize(role,action,{id,kind},initialState(true))));
test('reviewer can review a stored social post',()=>assert.doesNotThrow(()=>authorize('Content Reviewer','approval.decide',{id:'post-1'},initialState(true))));
for(const role of ['Admin','CMO','Sales','Content Reviewer','Viewer'])test(`${role} cannot grant workspace access`,()=>assert.throws(()=>validateMember(role,'owner','other','Viewer')));
test('founder grants only supported roles and cannot overwrite ownership',()=>{assert.doesNotThrow(()=>validateMember('Founder','owner','other','Sales'));assert.throws(()=>validateMember('Founder','owner','owner','Viewer'));assert.throws(()=>validateMember('Founder','owner','other','Founder'))});
for(const action of ['lead.update','lead.archive','email.reply'])test(`${action} preserves an in-flight send and blocks erasure`,()=>{const s=initialState(true),i=s.items.find(i=>i.id==='draft-1'),l=s.leads.find(l=>l.id===i.leadId);i.status='Sending';mutate(s,action,{id:l.id,leadId:l.id,optOut:true,classification:'Unsubscribe',body:'Stop email'},'Tester',true);assert.equal(i.status,'Sending');assert.throws(()=>mutate(s,'data.erase',{id:l.id,confirm:l.name},'Tester',true),/pending external/)});
test('pending calendar invitation blocks contact erasure',()=>{const s=initialState(true),i=s.items.find(i=>i.kind==='demo'),l=s.leads.find(l=>l.id===i.leadId);i.outcome='Invite pending';assert.throws(()=>mutate(s,'data.erase',{id:l.id,confirm:l.name},'Tester',true),/pending external/)});
test('erasure removes derived plans and delegated tasks',()=>{const s=initialState(true),l=s.leads.find(l=>l.temperature==='Hot');mutate(s,'plan.create',{},'Tester',true);const plan=s.items[0];mutate(s,'plan.execute',{id:plan.id},'Tester',true);mutate(s,'data.erase',{id:l.id,confirm:l.name},'Tester',true);assert.ok(!s.items.some(i=>i.referencedLeadIds?.includes(l.id)||i.body.includes(l.name)))});
test('pipeline creation preserves chosen stage',()=>{const s=initialState(false);mutate(s,'lead.create',{name:'QA Hospital',contact:'Tester',email:'qa@example.com',location:'Test',stage:'Interested'},'Tester',true);assert.equal(s.leads[0].stage,'Interested');assert.equal(s.leads[0].stageHistory[0].stage,'Interested')});
test('disabled studio blocks editing stored social posts despite payload kind',()=>{const s=initialState(true);s.disabledAgents.push('Content Studio');assert.throws(()=>mutate(s,'item.edit',{id:'post-1',kind:'edit',title:'Test',body:'Test'},'Tester',true),/Enable Content Studio/)});

test('demo outcome cannot clear an active invitation reservation',()=>{const s=initialState(true),i=s.items.find(i=>i.kind==='demo');i.outcome='Invite pending';assert.throws(()=>mutate(s,'demo.outcome',{id:i.id,outcome:'Interested',body:'QA'},'Tester',true),/pending calendar/)});
test('erasure blocks an in-flight derived social post',()=>{const s=initialState(true),l=s.leads[0];s.items.push({id:'derived',kind:'post',leadId:'',referencedLeadIds:[l.id],status:'Executing'});assert.throws(()=>mutate(s,'data.erase',{id:l.id,confirm:l.name},'Tester',true),/pending external/)});
test('new reply after reservation prevents provider send',()=>{const s=initialState(true),i=s.items.find(i=>i.id==='draft-1');i.status='Sending';i.sentAt=new Date().toISOString();assert.equal(reservationCanSend(s,i.id),true);mutate(s,'email.reply',{leadId:i.leadId,classification:'Positive',body:'Interested'},'Tester',true);assert.equal(reservationCanSend(s,i.id),false)});
