'use client';
import {useEffect,useState} from 'react';
import {Sparkles,Search,Check,ArrowUpRight,RefreshCw,Workflow,Plus,ShieldCheck} from 'lucide-react';
import {toast} from 'sonner';
import type {State,Item} from '@/shared/model';
import {metricsFor,factCatalog} from '@/shared/domain';
type Props={view:string;state:State;mode:string;act:(action:string,p?:any,success?:string)=>Promise<boolean>;refresh:()=>void;open:(i:Item)=>void;create:(kind:string)=>void};
export function Operations({view,state,mode,act,refresh,open,create}:Props){
 const [data,setData]=useState<any>({connections:[],runs:[]}),[input,setInput]=useState(''),[busy,setBusy]=useState(false),[campaign,setCampaign]=useState(''),[period,setPeriod]=useState('all'),[error,setError]=useState('');
 async function reload(){if(mode==='sample'){setData({connections:['Gmail','Calendar','LinkedIn','Instagram','Claude','Research'].map(name=>({name,configured:false,missing:[]})),runs:state.mockRuns||[],role:'Sample operator'});setError('');return}try{const r=await fetch('/api/operations?mode='+mode),d:any=await r.json();if(!r.ok)throw new Error(d.message);setData(d);setError('')}catch(e){setError((e as Error).message)}}
 useEffect(()=>{reload();const t=setInterval(reload,15000);return()=>clearInterval(t)},[mode,state.mockRuns]);
 async function run(action:string){setBusy(true);try{const r=await fetch('/api/operations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode,action,input})}),d:any=await r.json();if(!r.ok)throw new Error(d.message);toast.success(d.message);refresh();reload()}catch(e){toast.error((e as Error).message);reload()}finally{setBusy(false)}}
 const campaigns=state.items.filter(i=>i.kind==='campaign');const since=period==='all'?undefined:new Date(Date.now()-Number(period)*86400000).toISOString();const m=metricsFor(state,campaign||undefined,since);const percent=(n:number|null)=>n===null?'—':(n*100).toFixed(1)+'%';
 const list=(items:Item[])=>items.length?<div className="ops-list">{items.map(i=><button key={i.id} onClick={()=>open(i)}><div><strong>{i.title}</strong><small>{i.channel} · {i.status}{i.source?' · '+i.source.slice(0,80):''}</small></div><ArrowUpRight size={16}/></button>)}</div>:<p className="rail-note">No records yet. Create your first one above.</p>;
 if(error)return <div className="error-banner" role="alert">{error}<button onClick={reload}>Retry</button></div>;
 if(view==='Analytics')return <><section className="card"><div className="card-head"><h2>Growth performance</h2><div className="row"><select aria-label="Analytics campaign" value={campaign} onChange={e=>setCampaign(e.target.value)}><option value="">All campaigns</option>{campaigns.map(i=><option key={i.id} value={i.id}>{i.title}</option>)}</select><select aria-label="Reporting period" value={period} onChange={e=>setPeriod(e.target.value)}><option value="all">All time</option><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="90">Last 90 days</option></select></div></div><div className="ops-metrics">{[['Confirmed sends',m.sent],['Reply rate',percent(m.replyRate)],['Demo → interested',percent(m.demoConversion)],['Social engagement',percent(m.engagementRate)],['Median days per stage',m.velocity===null?'—':m.velocity.toFixed(1)],['Overdue tasks',m.overdue]].map(([label,value])=><div key={label}><small>{label}</small><strong>{value}</strong></div>)}</div><p className="rail-note">Email rates use provider-confirmed sends. Demo conversion is interested outcomes ÷ completed meetings. Social engagement uses evidence-tagged metric entries. “—” means there is insufficient data. The period filters activity; pipeline inventory is current.</p></section><section className="card mt"><div className="card-head"><h2>Campaign attribution</h2></div><div className="table-scroll"><table><thead><tr><th>CAMPAIGN</th><th>LEADS</th><th>HOT</th><th>WON</th><th>REPLY RATE</th></tr></thead><tbody>{campaigns.map(i=>{const k=metricsFor(state,i.id,since);return <tr key={i.id}><td><button className="text-button" onClick={()=>open(i)}>{i.title}</button></td><td>{k.leads}</td><td>{k.hot}</td><td>{k.won}</td><td>{percent(k.replyRate)}</td></tr>})}</tbody></table></div>{!campaigns.length&&<p className="rail-note">Assign hospitals to a campaign to measure attribution.</p>}</section></>;
 if(view==='Campaigns')return <><section className="card"><div className="card-head"><h2>Campaigns that connect the work</h2><button className="btn" onClick={()=>create('campaign')}><Plus size={16}/>New campaign</button></div><p className="rail-note">Create and approve a campaign brief, activate it, then assign hospital relationships. Every outbound message still requires its own approval.</p>{list(campaigns)}</section><div className="content-grid mt">{campaigns.filter(i=>i.status==='Active').map(i=>{const k=metricsFor(state,i.id);return <section className="card ops-panel" key={i.id}><span className="chip approved">Active campaign</span><h3>{i.title}</h3><p>{k.leads} hospitals · {k.hot} hot · {k.won} won · {k.sent} confirmed sends</p><button className="text-button" onClick={()=>open(i)}>Manage campaign <ArrowUpRight size={16}/></button></section>})}</div></>;
 if(view==='AI CMO Brain'||view==='Trends')return <><section className="brain-hero"><Sparkles size={38}/><div><div className="eyebrow">{view==='Trends'?'SOURCED RESEARCH':'GOSAKHA INTELLIGENCE'}</div><h2>{view==='Trends'?'Find the signals worth acting on.':'A plan your team can act on.'}</h2><p>{view==='Trends'?'Search public sources, keep the evidence, and convert useful findings into research tasks.':'Generate a plan from hospital stages and product knowledge. Review it, then delegate to tasks and drafts.'}</p><form className="ops-prompt" onSubmit={e=>{e.preventDefault();run(view==='Trends'?'research.search':'ai.plan')}}><input aria-label={view==='Trends'?'Research query':'AI planning prompt'} value={input} onChange={e=>setInput(e.target.value)} required maxLength={2000} placeholder={view==='Trends'?'e.g. Hyderabad hospital patient call experience':'e.g. Plan outreach for warm hospitals this week'}/><button className="btn light" disabled={busy||!data.connections.find((p:any)=>p.name===(view==='Trends'?'Research':'Claude'))?.configured}>{busy?'Working…':view==='Trends'?'Search sources':'Generate AI plan'}</button></form><small>{data.connections.find((p:any)=>p.name===(view==='Trends'?'Research':'Claude'))?.configured?'Provider configured; each run records its actual result.':'Connect '+(view==='Trends'?'Brave Search':'Claude')+' in Integrations to enable this action.'}</small><div className="row mt">{view==='AI CMO Brain'?<button className="btn light" disabled={busy} onClick={()=>act('plan.create',{},'Priorities prepared')}>Create priorities from saved records</button>:<button className="btn light" onClick={()=>create('trend')}>Add source manually</button>}</div></div></section><section className="card mt"><div className="card-head"><h2>{view==='Trends'?'Sources & research':'Plans awaiting your direction'}</h2></div>{list(state.items.filter(i=>i.kind===(view==='Trends'?'trend':'plan')))}</section></>;
 if(view==='Integrations')return <><section className="connection-banner"><ShieldCheck size={25}/><div><strong>Connections with visible evidence</strong><p>Configured means credentials are present. A successful operation in the run history confirms that action worked. Your role: {data.role||'Loading'}.</p></div><button className="btn secondary" onClick={reload}><RefreshCw size={16}/>Refresh</button></section>{error&&<p role="alert" className="error-banner">{error}</p>}<div className="agent-grid">{data.connections.map((p:any)=><section className="card ops-panel" key={p.name}><span className={'chip '+(p.configured?'approved':'neutral')}>{p.configured?'Configured · test required':'Not connected'}</span><h3>{p.name}</h3><p>{({Gmail:'Approved emails and reply detection.',Calendar:'Send a 30-minute demo invitation to the selected contact.',LinkedIn:'Publish approved text posts through the official API.',Instagram:'Prepare a public image, then publish its approved caption.',Claude:'Structured growth plans with reviewed task delegation.',Research:'Public search results with their original source URLs.'} as any)[p.name]}</p><details><summary>Setup requirements</summary><p className="soft">Configure server secrets through Site settings. Never add credentials to hospital notes or content.</p><ul>{p.missing.map((k:string)=><li key={k}><code>{k}</code></li>)}</ul>{p.configured&&<p>Required settings are present. Provider permissions and account access must also be valid.</p>}</details></section>)}</div><section className="card mt ops-panel"><h3>Background follow-ups</h3><p>The protected scheduler processes due, approved emails and posts. A server scheduler must call it while this dashboard is closed. Phase 8: unattended sending is not yet configured. No background scheduler is currently verified. The last actual scheduler runs appear below.</p><p className="soft">Two-day and three-day reminders start after confirmed sends. Replies, opt-outs, pauses and daily caps are checked again before sending.</p></section><RunHistory runs={data.runs}/></>;
 if(view==='Agent center')return <><section className="card ops-panel"><div className="row"><Workflow size={26}/><div><h2>Agent operations</h2><p>Sample runs use deterministic mock providers. Connected-provider runs are recorded separately in My workspace.</p></div><button className="btn secondary" onClick={reload}><RefreshCw size={16}/>Refresh runs</button></div></section><RunHistory runs={data.runs}/></>;
 return null;
}
function RunHistory({runs}:{runs:any[]}){
 const [status,setStatus]=useState('All runs'),[query,setQuery]=useState('');
 const label=(r:any)=>r.status==='Running'&&Date.now()-Date.parse(r.started_at)>120000?'Needs investigation':r.status;
 const filtered=runs.filter(r=>(status==='All runs'||label(r)===status)&&[r.agent,r.action,r.message].join(' ').toLowerCase().includes(query.toLowerCase()));
 return <section className="card mt"><div className="card-head"><div><h2>Agent run history</h2><small className="soft">Latest {runs.length} recorded runs</small></div><div className="run-filters"><input aria-label="Filter agent runs" placeholder="Find agent or action…" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Run status" value={status} onChange={e=>setStatus(e.target.value)}>{['All runs','Failed','Completed','Running','Needs investigation'].map(v=><option key={v}>{v}</option>)}</select></div></div><div className="run-summary">{['Completed','Failed','Running','Needs investigation'].map(v=><button key={v} aria-pressed={status===v} onClick={()=>setStatus(status===v?'All runs':v)}><span>{v}</span><strong>{runs.filter(r=>label(r)===v).length}</strong></button>)}</div><div className="table-scroll"><table><thead><tr><th>AGENT / ACTION</th><th>STATUS</th><th>STARTED (IST)</th><th>DURATION</th><th>RESULT</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td><strong>{r.agent}</strong><small>{r.action}</small></td><td><span className={'chip '+(r.status==='Completed'?'approved':r.status==='Failed'?'stopped':'review')}>{label(r)}</span></td><td>{new Date(r.started_at).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})}</td><td>{r.finished_at?Math.max(0,(Date.parse(r.finished_at)-Date.parse(r.started_at))/1000).toFixed(1)+'s':'—'}</td><td className="soft">{r.message||'Execution started'}</td></tr>)}</tbody></table></div>{!filtered.length&&<div className="run-empty"><Workflow size={24}/><h3>{runs.length?'No runs match these filters':'No workflow runs yet'}</h3><p>{runs.length?'Choose another status or clear your search.':'Run history will appear after you connect and operate an agent. CRM changes appear in the activity log.'}</p>{(query||status!=='All runs')&&<button className="text-button" onClick={()=>{setStatus('All runs');setQuery('')}}>Clear filters</button>}</div>}</section>
}
export function FactGuide(){return <details className="fact-guide"><summary>Brochure fact references</summary>{factCatalog.map(f=><p key={f.id}><strong>{f.id}</strong> · {f.text}</p>)}</details>}
