'use client';
import {useEffect,useState} from 'react';
import {X,Search,Bell,ChevronDown,ChevronRight,Building2,ArrowUpRight,Settings2,Plug,LogOut,LogIn,Plus,CalendarDays,ListChecks,ShieldCheck,LayoutDashboard,Clock3,AlertTriangle,CheckCheck} from 'lucide-react';
import {SidebarTrigger,useSidebar} from '@/frontend/components/ui/sidebar';
import {DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuItem,DropdownMenuLabel,DropdownMenuSeparator,DropdownMenuRadioGroup,DropdownMenuRadioItem} from '@/frontend/components/ui/dropdown-menu';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/frontend/components/ui/dialog';
import {Command,CommandInput,CommandList,CommandEmpty,CommandGroup,CommandItem} from '@/frontend/components/ui/command';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/frontend/components/ui/sheet';
import {roleAllows} from '@/shared/domain';
import type {State,Item} from '@/shared/model';
const initials=(name:string)=>name.split(/[\s@]+/).filter(Boolean).slice(0,2).map(n=>n[0]).join('').toUpperCase();
const when=(due:string)=>new Date(due).toLocaleString('en-IN',{timeZone:'Asia/Kolkata',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});
export function WorkspaceSwitch({mode,change,compact=false}:{mode:string;change:(mode:string)=>void;compact?:boolean}){return <DropdownMenu><DropdownMenuTrigger asChild><button className={compact?"breadcrumb-home":"workspace-label"} aria-label={compact?"Workspace menu":"Switch workspace"}><span className="workspace-avatar">G</span><span><strong>{compact?'Workspace':'GoSakha Innovations'}</strong>{!compact&&<small>{mode==='sample'?'Sample workspace':'My workspace'}</small>}</span><ChevronDown size={15}/></button></DropdownMenuTrigger><DropdownMenuContent className="workspace-menu" align="start" sideOffset={8}><DropdownMenuLabel>Choose your workspace</DropdownMenuLabel><DropdownMenuRadioGroup value={mode} onValueChange={change}><DropdownMenuRadioItem value="sample">Sample workspace</DropdownMenuRadioItem><DropdownMenuRadioItem value="live">My workspace</DropdownMenuRadioItem></DropdownMenuRadioGroup><DropdownMenuSeparator/><p className="menu-note">Sample and real hospital records are kept separate.</p></DropdownMenuContent></DropdownMenu>}
export function WorkspaceHeader({changeMode,view,go,state,user,role,mode,pages,open,create,authenticated,loaded}:{changeMode:(m:string)=>void;view:string;go:(v:string)=>void;state:State;user:string;role:string;mode:string;pages:string[];open:(d:any)=>void;create:(k:string)=>void;authenticated:boolean;loaded:boolean}){
 const {open:sidebarOpen,isMobile,openMobile,setOpenMobile}=useSidebar();const [command,setCommand]=useState(false),[query,setQuery]=useState(''),[notifications,setNotifications]=useState(false);
 useEffect(()=>{setOpenMobile(false)},[view,mode,setOpenMobile]);
 useEffect(()=>{if(!isMobile)return;const close=(e:MouseEvent)=>{if((e.target as Element)?.closest('[data-slot=sidebar-menu-button],.footer-nav,.brand'))setOpenMobile(false)};document.addEventListener('click',close);return()=>document.removeEventListener('click',close)},[isMobile,setOpenMobile]);
 useEffect(()=>{const handler=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){if(!document.querySelector('[role="dialog"]')||command){e.preventDefault();setCommand(o=>!o)}}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler)},[command]);
 const action=(fn:()=>void)=>{setCommand(false);setNotifications(false);fn()};
 const alerts=attentionItems(state);const q=query.toLowerCase().trim();
 const leads=state.leads.filter(l=>!l.archived&&[l.name,l.contact,l.email,l.location].join(' ').toLowerCase().includes(q)).slice(0,8);
 const records=state.items.filter(i=>[i.title,i.body,i.channel].join(' ').toLowerCase().includes(q)).slice(0,8);
 const navigate=(v:string)=>{setOpenMobile(false);go(v)};
 return <><header className="topbar"><div className="breadcrumb"><SidebarTrigger aria-label={isMobile?(openMobile?'Close navigation':'Open navigation'):(sidebarOpen?'Collapse navigation':'Expand navigation')} title="Toggle navigation (Ctrl+B)"/><WorkspaceSwitch compact mode={mode} change={changeMode}/><ChevronRight size={13}/><strong>{view}</strong></div><div className="top-actions"><button className="command-trigger" aria-label="Search workspace (Ctrl+K)" onClick={()=>{setQuery('');setCommand(true)}}><Search size={18}/><span>Search or jump to…</span><kbd>Ctrl K</kbd></button><DropdownMenu><DropdownMenuTrigger asChild><button className="header-icon quick-create" aria-label="Quick create" title="Quick create" disabled={!loaded||role==='Viewer'}><Plus size={19}/></button></DropdownMenuTrigger><DropdownMenuContent className="workspace-menu" align="end"><DropdownMenuLabel>Create in {mode==='sample'?'sample':'my'} workspace</DropdownMenuLabel>{[['lead','Hospital',Building2],['demo','Demo',CalendarDays],['task','Task',ListChecks],['post','Content draft',Plus]].filter(([k])=>roleAllows(role,k==='lead'?'lead.create':k==='post'?'content.generate':'item.create')).map(([k,label,Icon]:any)=><DropdownMenuItem key={k} onSelect={()=>create(k)}><Icon size={16}/>{label}</DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu><button className="header-icon" aria-label={'Attention inbox'+(alerts.length?' ('+alerts.length+')':'')} title="Attention inbox" onClick={()=>setNotifications(true)}><Bell size={19}/>{!!alerts.length&&<span className="header-badge">{alerts.length>99?'99+':alerts.length}</span>}</button><DropdownMenu><DropdownMenuTrigger asChild><button className="account-trigger" aria-label="Account menu"><span className="top-avatar">{authenticated?initials(user):'G'}</span><ChevronDown size={13}/></button></DropdownMenuTrigger><DropdownMenuContent className="workspace-menu account-menu" align="end"><DropdownMenuLabel><strong>{authenticated?user:'Welcome to GoSakha'}</strong><small>{authenticated?role+' · '+(mode==='sample'?'Sample workspace':'My workspace'):'Sign in to access your saved workspace'}</small></DropdownMenuLabel><DropdownMenuSeparator/><DropdownMenuItem onSelect={()=>navigate('Account & team')}><Building2 size={16}/>Account & team</DropdownMenuItem><DropdownMenuItem onSelect={()=>navigate('Settings')}><Settings2 size={16}/>Settings</DropdownMenuItem><DropdownMenuItem onSelect={()=>navigate('Integrations')}><Plug size={16}/>Connections</DropdownMenuItem><DropdownMenuItem onSelect={()=>navigate('Audit log')}><ShieldCheck size={16}/>Activity & audit</DropdownMenuItem><DropdownMenuSeparator/><DropdownMenuItem asChild><a href={authenticated?'/signout-with-chatgpt?return_to=%2F':'/signin-with-chatgpt?return_to=%2F'}>{authenticated?<LogOut size={16}/>:<LogIn size={16}/>} {authenticated?'Sign out':'Sign in with ChatGPT'}</a></DropdownMenuItem></DropdownMenuContent></DropdownMenu></div></header>
 <Dialog open={command} onOpenChange={setCommand}><DialogContent className="search-dialog"><DialogHeader className="sr-only"><DialogTitle>Search your workspace</DialogTitle><DialogDescription>Find hospitals, drafts and pages. Use arrow keys and Enter to open a result.</DialogDescription></DialogHeader><Command shouldFilter={false}><CommandInput aria-label="Search hospitals, records and pages" value={query} onValueChange={setQuery} placeholder="Find a hospital, draft, task or page…"/><CommandList>{!q&&<CommandGroup heading="Quick actions"><CommandItem disabled={!loaded||!roleAllows(role,'lead.create')} onSelect={()=>action(()=>create('lead'))}><Plus/>Add a hospital</CommandItem><CommandItem onSelect={()=>action(()=>navigate('Approvals'))}><ShieldCheck/>Review approvals</CommandItem></CommandGroup>}{leads.length>0&&<CommandGroup heading="Hospitals">{leads.map(l=><CommandItem key={l.id} value={l.id} onSelect={()=>action(()=>open({kind:'lead',id:l.id}))}><Building2/><span><strong>{l.name}</strong><small>{l.contact} · {l.location}</small></span><span className={'chip '+l.temperature.toLowerCase()}>{l.temperature}</span></CommandItem>)}</CommandGroup>}{q&&records.length>0&&<CommandGroup heading="Workspace records">{records.map(i=><CommandItem key={i.id} value={i.id} onSelect={()=>action(()=>open({kind:'item',id:i.id}))}><ListChecks/><span><strong>{i.title}</strong><small>{i.channel} · {i.status}</small></span></CommandItem>)}</CommandGroup>}<CommandGroup heading="Jump to">{pages.filter(v=>v.toLowerCase().includes(q)).map(v=><CommandItem key={v} value={v} onSelect={()=>action(()=>navigate(v))}><ArrowUpRight/>{v}</CommandItem>)}</CommandGroup><CommandEmpty>No matching records. Try a hospital name or page.</CommandEmpty></CommandList><div className="command-hint"><span>↑ ↓ Navigate · Enter Open</span><span>Esc Close</span></div></Command></DialogContent></Dialog>
 <Sheet open={notifications} onOpenChange={setNotifications}><SheetContent className="attention-sheet"><SheetHeader><SheetTitle>Attention inbox <span className="count">{alerts.length}</span></SheetTitle><SheetDescription>Approvals, overdue work and outcomes that need a decision.</SheetDescription></SheetHeader><div className="attention-list">{alerts.length?alerts.map(a=><button key={a.item.id} onClick={()=>action(()=>open({kind:'item',id:a.item.id}))}><span className={'attention-icon '+a.tone}><a.icon size={19}/></span><span><small>{a.label}</small><strong>{a.item.title}</strong><p>{a.item.due?when(a.item.due)+' IST':a.item.channel+' · '+a.item.status}</p></span><ChevronRight size={16}/></button>):<div className="empty"><CheckCheck size={30}/><h3>Nothing needs attention</h3><p>New approvals and overdue actions will appear here.</p></div>}</div><div className="attention-footer"><button className="btn secondary" onClick={()=>action(()=>navigate('Tasks'))}>All tasks</button><button className="btn" onClick={()=>action(()=>navigate('Approvals'))}>Review approvals</button></div></SheetContent></Sheet></>;
}
function attentionItems(s:State){return s.items.flatMap(i=>{if(['Delivery uncertain','Publication uncertain'].includes(i.status)||i.outcome==='Invite uncertain')return [{item:i,label:'Check provider outcome',tone:'urgent',icon:AlertTriangle}];if(i.status==='Pending approval')return [{item:i,label:'Approval needed',tone:'review',icon:ShieldCheck}];if(i.due&&Date.parse(i.due)<Date.now()&&((i.kind==='task'&&i.status==='Open')||(i.kind==='demo'&&i.status==='Booked')))return [{item:i,label:i.kind==='demo'?'Record meeting outcome':'Overdue task',tone:'urgent',icon:Clock3}];return []}).sort((a,b)=>(a.tone==='urgent'?0:1)-(b.tone==='urgent'?0:1))}
export function FocusQueue({state,open,go}:{state:State;open:(d:any)=>void;go:(v:string)=>void}){const all=attentionItems(state);return <section className="focus-queue card"><div className="card-head"><div><span className="eyebrow">TODAY’S FOCUS</span><h2>{all.length?`${all.length} actions need your attention`:'You’re up to date'}</h2></div><button className="text-button" onClick={()=>go('Tasks')}>View tasks <ArrowUpRight size={15}/></button></div>{all.length?<div className="focus-items">{all.slice(0,3).map(a=><button key={a.item.id} onClick={()=>open({kind:'item',id:a.item.id})}><span className={'attention-icon '+a.tone}><a.icon size={18}/></span><span><small>{a.label}</small><strong>{a.item.title}</strong></span><ChevronRight size={15}/></button>)}</div>:<p className="rail-note">Approvals, overdue tasks and meeting outcomes will appear here when they need your review.</p>}</section>}

export function MobileNavigationClose(){const {isMobile,setOpenMobile}=useSidebar();return isMobile?<button className="mobile-nav-close" aria-label="Close mobile navigation" onClick={()=>setOpenMobile(false)}><X size={20}/></button>:null}
