import {assertClaims,checkClaims,classifyReply} from './domain.ts';
export type Lead={id:string;name:string;contact:string;email:string;location:string;type:string;source:string;score:number;temperature:string;stage:string;nextAction:string;optOut:boolean;notes:string;updatedAt:string;archived?:boolean;campaignId?:string;stageHistory?:{stage:string;at:string}[]};
export type Item={id:string;kind:string;title:string;body:string;status:string;channel:string;leadId:string;due:string;createdAt:string;source:string;step?:number;sentAt?:string;threadId?:string;delayDays?:number;sequenceId?:string;outcome?:string;providerId?:string;decisionBy?:string;decisionAt?:string;versions?:string[];campaignId?:string;mediaUrl?:string;referencedLeadIds?:string[];reviewHistory?:{decision:string;actor:string;at:string;reason:string}[];metrics?:{impressions:number;likes:number;comments:number;shares:number;source:string;at:string};actions?:{kind:string;title:string;body:string;leadId?:string;source:string;done?:boolean}[]};
export type Event={id:string;type:string;actor:string;message:string;entityId:string;createdAt:string;status?:string;hospitalId?:string;productId?:string;campaignId?:string;correlationId?:string;workflowRunId?:string;simulated?:boolean;metadata?:Record<string,unknown>};
export type State={mockRuns?:{id:string;agent:string;action:string;status:string;started_at:string;finished_at:string;message:string}[];leads:Lead[];items:Item[];events:Event[];settings:{sender:string;followup1:number;followup2:number;dailyCap:number;paused:boolean};disabledAgents:string[]};
export const stages=['New','Contacted','Interested','Demo','Proposal','Negotiation','Won','Lost'];
export const agentNames=['AI CMO Brain','Gmail Agent','Email Outreach','Lead Intelligence','LinkedIn Agent','Instagram Agent','Content Studio','CRM Agent','Campaign Intelligence','Trends Agent','Notifications'];
export const uid=()=>{if(typeof crypto.randomUUID==='function')return crypto.randomUUID();const b=crypto.getRandomValues(new Uint8Array(16));b[6]=(b[6]&15)|64;b[8]=(b[8]&63)|128;const h=Array.from(b,n=>n.toString(16).padStart(2,'0')).join('');return h.slice(0,8)+'-'+h.slice(8,12)+'-'+h.slice(12,16)+'-'+h.slice(16,20)+'-'+h.slice(20)};
export function initialState(sample=false):State{
 const now=new Date(), iso=(offset:number)=>new Date(now.getTime()+offset*3600000).toISOString();
 const demoDay=(days:number)=>{const d=new Date(now.getTime()+days*86400000);d.setUTCHours(4,30,0,0);return d.toISOString()};
 const state:State={leads:[],items:[],events:[],settings:{sender:'GoSakha team',followup1:2,followup2:3,dailyCap:25,paused:false},disabledAgents:[]};
 if(!sample)return state;
 state.leads=[['Aarunya Multispeciality','Dr. Ananya Rao','Narsingi','Hot','Demo',92,'Confirm Sakha walkthrough','Email'],['Lotus Care Hospital','Vikram Sharma','Kokapet','Hot','Interested',86,'Share appointment booking demo','LinkedIn'],['Greenfield Women & Children','Dr. Meera Patel','Gachibowli','Hot','Proposal',90,'Follow up on proposal','Referral'],['Horizon Health Clinic','Arjun Reddy','Narsingi','Warm','Contacted',63,'Follow up in two days','Email'],['Nova Diagnostics','Priya Menon','Madhapur','Warm','Interested',71,'Arrange discovery call','Call'],['WellSpring Hospital','Dr. R. Kumar','Kokapet','Cold','New',35,'Verify decision-maker','Research'],['Cedar Family Clinic','Kavya Singh','Manikonda','Warm','Contacted',58,'Review reply','Email'],['Unity Specialty Hospital','Sanjay Rao','Financial District','Cold','New',28,'Research patient-call workflow','Research']].map((r,i)=>({id:'lead-'+i,name:String(r[0]),contact:String(r[1]),email:'contact'+i+'@example.com',location:String(r[2]),type:i===4?'Diagnostic center':i===3||i===6?'Clinic':'Hospital',temperature:String(r[3]),stage:String(r[4]),score:Number(r[5]),nextAction:String(r[6]),source:String(r[7]),optOut:false,notes:'Fictional hospital sales prospect for Sakha, a B2B AI voice assistant. Decision-maker: '+(i%2?'Hospital administrator':'Medical director')+'. Not a verified hospital or contact.',updatedAt:iso(-i)}));
 state.items=[{id:'draft-1',kind:'email',title:'A 24/7 voice assistant for Lotus Care Hospital',body:'Hi Vikram,\n\nI’m reaching out from GoSakha. Sakha supports around-the-clock hospital calls, specialist routing and appointment booking.\n\nWould a 15-minute walkthrough be useful for your team?\n\nBest,\nGoSakha team\n\nIf you prefer no further emails, simply reply “unsubscribe”.',status:'Pending approval',channel:'Email',leadId:'lead-1',due:iso(0),createdAt:iso(-1),source:'GoSakha brochure · HK-002, HK-003, HK-004'}, {id:'post-1',kind:'post',title:'Better patient journeys start with a conversation',body:'From a hospital call to a booked appointment. Sakha helps patients reach the right specialist, with appointment reference numbers and a live hospital dashboard.\n\nSee how it works: request a GoSakha walkthrough.\n\n#HealthcareAI #PatientExperience',status:'Pending approval',channel:'LinkedIn',leadId:'',due:iso(26),createdAt:iso(-2),source:'GoSakha brochure · HK-002, HK-004'}, {id:'post-2',kind:'post',title:'Your hospital, available around the clock',body:'Meet Sakha, your hospital’s 24/7 AI assistant. From patient calls to specialist routing and appointment booking.\n\nConnect with GoSakha for a walkthrough. #HealthcareAI',status:'Draft',channel:'Instagram',leadId:'',due:iso(48),createdAt:iso(-4),source:'GoSakha brochure · HK-002, HK-003, HK-004'}, {id:'demo-1',kind:'demo',title:'Sakha product walkthrough',body:'Focus on specialist routing and the hospital dashboard. Internal booking; calendar invite not sent.',status:'Booked',channel:'Meeting',leadId:'lead-0',due:demoDay(1),createdAt:iso(-5),source:'Fictional Sakha sales demo'}, {id:'demo-2',kind:'demo',title:'Sakha demo · appointment workflow',body:'Understand the current call handling process. Internal booking; calendar invite not sent.',status:'Booked',channel:'Meeting',leadId:'lead-4',due:demoDay(2),createdAt:iso(-6),source:'Fictional Sakha sales demo'}, {id:'campaign-1',kind:'campaign',title:'Hyderabad hospital introductions',body:'Introduce Sakha to hospital operations teams in Narsingi and Kokapet. Goal: qualified walkthroughs.',status:'Draft',channel:'Email',leadId:'',due:iso(168),createdAt:iso(-20),source:'Sample campaign'}, {id:'task-1',kind:'task',title:'Follow up with Horizon Health Clinic',body:'Ask whether a short product walkthrough would be useful.',status:'Open',channel:'Email',leadId:'lead-3',due:iso(-3),createdAt:iso(-10),source:'Sample task'}];
 state.events=[['DEMO_BOOKED','CRM Agent','Sakha walkthrough added for Aarunya Multispeciality','demo-1'],['EMAIL_APPROVAL_REQUESTED','Email Outreach','Introduction to Lotus Care is ready for review','draft-1'],['CONTENT_DRAFT_CREATED','Content Studio','LinkedIn post prepared with brochure references','post-1'],['LEAD_QUALIFIED','Lead Intelligence','Greenfield Women & Children moved to the hot queue','lead-2']].map((r,i)=>({id:'event-'+i,type:r[0],actor:r[1],message:r[2],entityId:r[3],createdAt:iso(-i*.4),status:'Completed',productId:'sakha',hospitalId:i===0?'lead-0':i===1?'lead-1':i===3?'lead-2':'',campaignId:'campaign-1',correlationId:'seed-workflow-'+i,workflowRunId:'seed-workflow-'+i,simulated:true,metadata:{provider:'Fictional seed',externalAction:false}}));return state;
}
export function record(s:State,type:string,actor:string,message:string,entityId=''){const id=uid(),item=s.items.find(i=>i.id===entityId),hospitalId=item?.leadId||(s.leads.some(l=>l.id===entityId)?entityId:'');s.events.unshift({id,type,actor,message,entityId,createdAt:new Date().toISOString(),status:type.includes('FAILED')?'Failed':type.includes('STARTED')?'Started':'Completed',hospitalId,productId:'sakha',campaignId:item?.campaignId||s.leads.find(l=>l.id===hospitalId)?.campaignId||'',correlationId:id,workflowRunId:id,metadata:{source:'Workspace action'}});}
const required=(v:any,label:string,max=5000)=>{if(typeof v!=='string'||!v.trim()||v.length>max)throw new Error(label+' is required and must be under '+max+' characters.');return v.trim()};
const date=(v:string)=>{if(!v||!Number.isFinite(Date.parse(v)))throw new Error('Choose a valid date and time.');return new Date(v).toISOString()};
export function mutate(s:State,action:string,p:any,actor:string,sample:boolean){
 const now=new Date().toISOString();
 const lead=()=>{const l=s.leads.find(x=>x.id===p.id||x.id===p.leadId);if(!l)throw new Error('Hospital record not found.');return l};
 const item=()=>{const i=s.items.find(x=>x.id===p.id);if(!i)throw new Error('Record not found.');return i};
 if(['item.create','item.submit','item.edit'].includes(action)&&(action==='item.create'?p.kind:s.items.find(i=>i.id===p.id)?.kind)==='post'&&s.disabledAgents.includes('Content Studio'))throw new Error('Enable Content Studio first.');
 if(action==='lead.create'){
 if(p.stage&&!stages.includes(p.stage))throw new Error('Invalid pipeline stage.');const name=required(p.name,'Hospital',160),email=String(p.email||'').trim().toLowerCase();if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new Error('Enter a valid business email.');
 if(s.leads.some(l=>(email&&l.email.toLowerCase()===email)||l.name.toLowerCase()===name.toLowerCase()))throw new Error('This hospital or email already exists.');
 const l:Lead={id:uid(),name,email,contact:required(p.contact,'Contact',120),location:required(p.location,'Location',120),type:p.type||'Hospital',source:p.source||'Manual',score:30,temperature:'Cold',stage:p.stage||'New',nextAction:'Qualify hospital and verify contact',optOut:false,notes:String(p.notes||'').slice(0,4000),updatedAt:now,campaignId:p.campaignId||undefined,stageHistory:[{stage:p.stage||'New',at:now}]};s.leads.push(l);record(s,'LEAD_FOUND',actor,name+' added to hospital pipeline',l.id);
 }else if(action==='lead.update'){
 const l=lead();if(p.stage){if(!stages.includes(p.stage))throw new Error('Invalid pipeline stage.');if(l.stage!==p.stage){l.stageHistory=[...(l.stageHistory||[{stage:l.stage,at:l.updatedAt}]),{stage:p.stage,at:now}];l.stage=p.stage}}if(p.temperature){if(!['Hot','Warm','Cold'].includes(p.temperature))throw new Error('Invalid temperature.');l.temperature=p.temperature;l.score=p.temperature==='Hot'?85:p.temperature==='Warm'?60:30}if(typeof p.notes==='string')l.notes=p.notes.slice(0,4000);if(p.nextAction)l.nextAction=String(p.nextAction).slice(0,300);if(typeof p.optOut==='boolean'){l.optOut=p.optOut;if(l.optOut)s.items.filter(i=>i.leadId===l.id&&['email','sequence'].includes(i.kind)&&!['Sending','Executing','Delivery uncertain','Sent','Replied','Rejected'].includes(i.status)).forEach(i=>i.status='Stopped')}if(p.campaignId!==undefined){if(p.campaignId&&!s.items.some(i=>i.id===p.campaignId&&i.kind==='campaign'))throw new Error('Campaign not found.');l.campaignId=p.campaignId}l.updatedAt=now;record(s,'CRM_STAGE_CHANGED',actor,l.name+' updated: '+l.stage+(l.optOut?' · opted out':''),l.id);
 }else if(action==='email.draft'){
 if(s.disabledAgents.includes('Email Outreach'))throw new Error('Enable Email Outreach in Agent center first.');const l=lead();if(l.optOut)throw new Error('This contact opted out. Outreach is blocked.');if(!l.email)throw new Error('Add a verified business email before preparing outreach.');
 const seq=uid();const body=`Hi ${l.contact.split(' ')[0]},\n\nI’m reaching out from GoSakha. Sakha supports hospital calls around the clock, routes callers to the right specialist and books appointments.\n\nWould a 15-minute walkthrough be useful for ${l.name}?\n\nBest,\n${s.settings.sender}\nGoSakha Innovations LLP\n\nTo stop further emails, reply “unsubscribe”.`;
 s.items.unshift({id:uid(),kind:'email',title:`A 24/7 voice assistant for ${l.name}`,body,status:'Pending approval',channel:'Email',leadId:l.id,due:now,createdAt:now,source:'GoSakha brochure · HK-002, HK-003, HK-004',step:0,sequenceId:p.sequence?seq:undefined});
 if(p.sequence){for(let step=1;step<=2;step++)s.items.push({id:uid(),kind:'email',title:(step===1?'Following up: ':'A final note: ')+`Sakha for ${l.name}`,body:`Hi ${l.contact.split(' ')[0]},\n\n${step===1?'Following up on my earlier note. Would a short Sakha walkthrough be useful for your team? Happy to work around your schedule.':'One last follow-up. If now is not the right time, no problem. Let us know if you would like to explore Sakha in the future.'}\n\nBest,\n${s.settings.sender}\nGoSakha Innovations LLP\n\nTo stop further emails, reply “unsubscribe”.`,status:'Pending approval',channel:'Email',leadId:l.id,due:'',createdAt:now,source:'GoSakha outreach templates · HK-002, HK-003, HK-004',step,sequenceId:seq,delayDays:step===1?s.settings.followup1:s.settings.followup2});}if(p.sequence)s.items.push({id:seq,kind:'sequence',title:'Sakha introduction · '+l.name,body:'Introduction → '+s.settings.followup1+' days → reminder → '+s.settings.followup2+' days → final follow-up',status:'Waiting for initial send',channel:'Email',leadId:l.id,due:'',createdAt:now,source:'User-configured sequence'});
 record(s,'EMAIL_APPROVAL_REQUESTED','Email Outreach','Outreach prepared for '+l.name,l.id);
 }else if(action==='content.generate'){
 if(s.disabledAgents.includes('Content Studio'))throw new Error('Enable Content Studio first.');const platform=p.channel==='Instagram'?'Instagram':'LinkedIn';const i:Item={id:uid(),kind:'post',title:platform==='Instagram'?'Meet Sakha. A clearer path to an appointment.':'From a hospital call to the right specialist.',body:platform==='Instagram'?'Meet Sakha, GoSakha’s AI hospital assistant.\n\nAvailable around the clock, Sakha supports specialist routing and appointment booking.\n\nCurious how this could work for your hospital? Contact GoSakha for a walkthrough.\n\n#HealthcareAI #PatientExperience':'A patient journey often starts with a phone call.\n\nSakha is designed to support hospital calls around the clock, help callers reach the right specialist, and book appointments with a confirmation reference.\n\nIf you manage hospital operations, we would love to understand your current call workflow and show you Sakha.\n\nRequest a 15-minute GoSakha walkthrough.',status:'Draft',channel:platform,leadId:'',due:'',createdAt:now,source:'GoSakha brochure · HK-002, HK-003, HK-004 · template-generated, human review required'};s.items.unshift(i);record(s,'CONTENT_DRAFT_CREATED','Content Studio',platform+' draft prepared from Sakha knowledge',i.id);
 }else if(action==='item.create'){
 if(!['post','campaign','task','trend','demo'].includes(p.kind))throw new Error('Invalid record type.');if(p.kind==='demo')lead();if(p.channel&&!['Email','LinkedIn','Instagram','Meeting','Internal'].includes(p.channel))throw new Error('Invalid channel.');
 if(p.kind==='trend'){const u=new URL(required(p.source,'Source URL'));if(!['https:','http:'].includes(u.protocol))throw new Error('Use a public http or https source.');}
 const i:Item={id:uid(),kind:p.kind,title:required(p.title,'Title',200),body:required(p.body,'Details'),status:p.kind==='demo'?'Booked':p.kind==='task'?'Open':p.kind==='trend'?'New':'Draft',channel:p.channel||'Internal',leadId:p.leadId||'',due:p.due?date(p.due):'',createdAt:now,campaignId:p.campaignId||undefined,mediaUrl:p.mediaUrl||undefined,source:p.kind==='trend'?p.source:p.source||'User-authored · requires fact review'};if(p.kind==='demo'&&!i.due)throw new Error('Choose a meeting time.');s.items.unshift(i);if(p.kind==='demo'){const l=lead();l.stageHistory=[...(l.stageHistory||[{stage:l.stage,at:l.updatedAt}]),{stage:'Demo',at:now}];l.stage='Demo';l.updatedAt=now;l.temperature='Hot'}record(s,p.kind==='demo'?'DEMO_BOOKED':p.kind.toUpperCase()+'_CREATED',actor,i.title,i.id);
 }else if(action==='item.edit'){
 const i=item();if(!['Draft','Pending approval','Revised'].includes(i.status))throw new Error('Only draft or pending content can be edited.');i.versions=[...(i.versions||[]),i.body];i.body=required(p.body,'Content');if(typeof p.source==='string')i.source=p.source.slice(0,2000);if(typeof p.mediaUrl==='string')i.mediaUrl=p.mediaUrl.slice(0,2000);i.decisionAt=undefined;i.decisionBy=undefined;i.status='Draft';record(s,'CONTENT_REVISED',actor,i.title,i.id);
 }else if(action==='item.submit'){
 const i=item();if(!['email','post','campaign'].includes(i.kind)||!['Draft','Revised'].includes(i.status))throw new Error('This item cannot be submitted.');assertClaims(i);i.status='Pending approval';record(s,'APPROVAL_REQUESTED',actor,i.title,i.id);
 }else if(action==='approval.decide'){
 const i=item();if(i.status!=='Pending approval')throw new Error('This item is no longer awaiting approval.');if(!['Approved','Rejected','Revised'].includes(p.decision))throw new Error('Invalid decision.');if(i.leadId&&s.leads.find(l=>l.id===i.leadId)?.optOut&&p.decision==='Approved')throw new Error('Contact opted out. Approval blocked.');if(p.decision==='Approved')assertClaims(i);i.reviewHistory=[...(i.reviewHistory||[]),{decision:p.decision,actor,at:now,reason:String(p.reason||'Human reviewed content and source references').slice(0,1000)}];i.status=p.decision;i.decisionBy=actor;i.decisionAt=now;record(s,'APPROVAL_'+p.decision.toUpperCase(),actor,i.title,i.id);
 }else if(action==='email.reply'){
 const l=lead();const classification=p.classification==='Auto'?classifyReply(String(p.body||'')):p.classification;if(!['Positive','Objection','Unsubscribe','Bounce','Neutral'].includes(classification))throw new Error('Choose a reply classification.');const note=required(p.body,'Reply notes');
 s.items.filter(i=>i.leadId===l.id&&['email','sequence'].includes(i.kind)&&!['Sending','Executing','Delivery uncertain','Rejected','Replied'].includes(i.status)).forEach(i=>i.status=i.kind==='email'&&i.status==='Sent'?'Replied':'Stopped');if(classification==='Unsubscribe'||classification==='Bounce')l.optOut=true;if(classification==='Positive'){l.temperature='Hot';l.score=90;l.stage='Interested';l.nextAction='Schedule a Sakha demo'}else if(classification==='Objection'){l.temperature='Warm';l.nextAction='Review objection and prepare a personal reply'}s.items.unshift({id:uid(),kind:'reply',title:classification+' reply · '+l.name,body:note,status:'Recorded manually',channel:'Email',leadId:l.id,due:'',createdAt:now,source:'Human recorded reply; not a Gmail sync'});record(s,'EMAIL_REPLY_RECORDED',actor,classification+' reply for '+l.name,l.id);
 }else if(action==='demo.outcome'){
 const i=item();if(i.kind!=='demo'||i.status!=='Booked')throw new Error('This meeting is not awaiting an outcome.');if(['Invite pending','Invite uncertain'].includes(i.outcome||''))throw new Error('Resolve the pending calendar invitation before recording an outcome.');if(!['Interested','Objection','Lost','No show'].includes(p.outcome))throw new Error('Invalid outcome.');i.status=p.outcome==='No show'?'No show':'Completed';i.outcome=p.outcome;i.body=required(p.body,'Meeting notes');const l=s.leads.find(l=>l.id===i.leadId);if(l){l.stageHistory=[...(l.stageHistory||[{stage:l.stage,at:l.updatedAt}]),{stage:p.outcome==='Interested'?'Proposal':p.outcome==='Lost'?'Lost':l.stage,at:now}];l.updatedAt=now;l.stage=p.outcome==='Interested'?'Proposal':p.outcome==='Lost'?'Lost':l.stage;l.nextAction=p.outcome==='No show'?'Reschedule meeting':p.outcome==='Interested'?'Prepare proposal':'Follow up on meeting';}s.items.unshift({id:uid(),kind:'task',title:(p.outcome==='No show'?'Reschedule: ':'Follow up: ')+i.title,body:i.body,status:'Open',channel:'Internal',leadId:i.leadId,campaignId:i.campaignId,due:new Date(Date.now()+86400000).toISOString(),createdAt:now,source:'Meeting outcome'});record(s,'DEMO_'+(i.status==='No show'?'NO_SHOW':'COMPLETED'),actor,i.title+' · '+p.outcome,i.id);
 }else if(action==='task.complete'){const i=item();if(i.kind!=='task')throw new Error('Invalid task.');i.status='Completed';record(s,'TASK_COMPLETED',actor,i.title,i.id);
 }else if(action==='trend.convert'){const i=item();if(i.kind!=='trend'||i.status==='Converted')throw new Error('This trend has already been converted.');i.status='Converted';s.items.unshift({...i,id:uid(),kind:'task',title:'Research content angle: '+i.title,status:'Open',createdAt:now});record(s,'TREND_CONVERTED',actor,i.title,i.id);
 }else if(action==='plan.create'){
 if(s.disabledAgents.includes('AI CMO Brain'))throw new Error('Enable AI CMO Brain first.');const hot=s.leads.filter(l=>l.temperature==='Hot'&&!l.optOut&&!['Won','Lost'].includes(l.stage));const pending=s.items.filter(i=>i.status==='Pending approval');const recommendations=[pending.length?`Review ${pending.length} pending approvals before starting new outreach.`:'Prepare personalized outreach for verified business contacts.',hot.length?`Prioritize ${hot.slice(0,3).map(l=>l.name).join(', ')} for a demo or next conversation.`:'Qualify new hospitals and record decision-maker details.','Review follow-ups and stop sequences where a reply or opt-out has been recorded.'];s.items.unshift({id:uid(),kind:'plan',referencedLeadIds:hot.slice(0,3).map(l=>l.id),title:'Daily growth priorities',body:recommendations.join('\n\n'),status:'Proposed',channel:'Internal',leadId:'',due:'',createdAt:now,source:'Rule-based plan from current records · no LLM connected'});record(s,'AI_PLAN_CREATED','AI CMO Brain','Daily priorities prepared from current pipeline');
 }else if(action==='settings.save'){
 for(const key of ['followup1','followup2','dailyCap'] as const){const n=Number(p[key]);if(!Number.isInteger(n)||n<1||n>(key==='dailyCap'?50:30))throw new Error('Use delays of 1–30 days and a daily cap of 1–50.');s.settings[key]=n}s.settings.sender=required(p.sender,'Sender name',120);s.settings.paused=!!p.paused;record(s,'SETTINGS_UPDATED',actor,'Follow-up schedule and sending preferences updated');
 }else if(action==='agent.toggle'){
 if(!agentNames.includes(p.name))throw new Error('Unknown agent.');s.disabledAgents=s.disabledAgents.includes(p.name)?s.disabledAgents.filter(a=>a!==p.name):[...s.disabledAgents,p.name];record(s,'AGENT_STATE_CHANGED',actor,p.name+' '+(s.disabledAgents.includes(p.name)?'disabled':'enabled'));
 }else if(action==='campaign.launch'){
 const i=item();if(i.kind!=='campaign'||i.status!=='Approved')throw new Error('Approve the campaign brief first.');i.status='Active';record(s,'CAMPAIGN_LAUNCHED',actor,i.title+' activated; outbound items require individual approval',i.id);
 }else if(action==='campaign.complete'){
 const i=item();if(i.kind!=='campaign'||i.status!=='Active')throw new Error('Campaign is not active.');i.status='Completed';record(s,'CAMPAIGN_COMPLETED',actor,i.title,i.id);
 }else if(action==='metrics.record'){
 const i=item();if(i.kind!=='post')throw new Error('Select a social post.');const values=['impressions','likes','comments','shares'].map(k=>Number(p[k]));if(values.some(n=>!Number.isInteger(n)||n<0))throw new Error('Use nonnegative whole numbers.');i.metrics={impressions:values[0],likes:values[1],comments:values[2],shares:values[3],source:required(p.source,'Metric evidence',1000),at:now};record(s,'METRICS_RECORDED',actor,i.title+' · manually entered with evidence',i.id);
 }else if(action==='lead.archive'){
 const l=lead();l.archived=true;l.optOut=true;s.items.filter(i=>i.leadId===l.id&&['email','sequence'].includes(i.kind)&&!['Sending','Executing','Delivery uncertain','Sent','Replied'].includes(i.status)).forEach(i=>i.status='Stopped');record(s,'LEAD_ARCHIVED',actor,l.name+' archived; outreach stopped',l.id);
 }else if(action==='data.erase'){
 const l=lead();if(p.confirm!==l.name)throw new Error('Enter the exact hospital name to erase its contact data.');const linked=new Set(s.items.filter(i=>i.leadId===l.id||i.referencedLeadIds?.includes(l.id)||i.actions?.some(a=>a.leadId===l.id)||(i.kind==='plan'&&!i.referencedLeadIds)).map(i=>i.id));if(s.items.some(i=>linked.has(i.id)&&(['Sending','Executing','Delivery uncertain','Publication uncertain'].includes(i.status)||['Invite pending','Invite uncertain'].includes(i.outcome||''))))throw new Error('Wait until the pending external action is resolved.');s.items=s.items.filter(i=>!linked.has(i.id));s.events=s.events.filter(e=>e.entityId!==l.id&&!linked.has(e.entityId));s.leads=s.leads.filter(x=>x.id!==l.id);record(s,'CONTACT_ERASED',actor,'Contact and linked workspace records erased');
 }else if(action==='plan.execute'){
 const i=item();if(i.kind!=='plan'||i.status!=='Proposed')throw new Error('Plan already executed or unavailable.');const actions:NonNullable<Item["actions"]>=i.actions||i.body.split('\n\n').map(body=>({kind:'task',title:body.slice(0,140),body,source:i.source}));if(actions.some(a=>a.kind==='post')&&s.disabledAgents.includes('Content Studio'))throw new Error('Enable Content Studio first.');for(const a of actions){if(a.kind==='email'&&a.leadId){mutate(s,'email.draft',{leadId:a.leadId,sequence:true},actor,sample)}else s.items.unshift({id:uid(),kind:a.kind==='post'?'post':'task',referencedLeadIds:i.referencedLeadIds,title:a.title,body:a.body,status:a.kind==='post'?'Draft':'Open',channel:a.kind==='post'?'LinkedIn':'Internal',leadId:a.leadId||'',due:'',createdAt:now,source:a.source});}i.status='Executed';record(s,'PLAN_DELEGATED',actor,i.title+' delegated to drafts and tasks; no external actions',i.id);
 }else if(action==='sample.execute'){
 if(!sample)throw new Error('Simulation is only available in sample mode.');const i=item();assertClaims(i);if(i.status!=='Approved')throw new Error('Human approval is required first.');if(s.settings.paused)throw new Error('Outreach is paused in Settings.');if(i.leadId&&s.leads.find(l=>l.id===i.leadId)?.optOut)throw new Error('Contact opted out.');i.status=i.kind==='email'?'Simulated send':i.kind==='campaign'?'Simulated active':'Simulated publish';record(s,'SIMULATION_COMPLETED',actor,i.title+' · sample only, no external action',i.id);
 }else throw new Error('Unknown action.');return s;
}
